name: Build Excalidraw Icons & Emojis Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Fetch Fluent UI SVG assets
        run: |
          python scripts/fetch_icons.py \
            --output metadata/icons.json \
            --download-dir vendor/icons \
            --force

      - name: Convert icons to Excalidraw
        run: |
          python scripts/svg_to_excalidraw.py \
            --input-dir vendor/icons/assets \
            --output-dir artifacts/excalidraw

      - name: Fetch Fluent UI Emoji assets
        run: |
          python scripts/fetch_emojis.py \
            --output metadata/emojis.json \
            --download-dir vendor/emojis \
            --force

      - name: Convert emojis to Excalidraw
        run: |
          python scripts/emoji_to_excalidraw.py \
            --input-dir vendor/emojis/assets \
            --output-dir artifacts/excalidraw_emojis

      - name: Combine all icons into a single board
        run: |
          python scripts/combine_excalidraw.py \
            --input-dir artifacts/excalidraw \
            --output artifacts/all_icons.excalidraw \
            --exclude-regular

      - name: Group icons into categories
        run: |
          python scripts/combine_excalidraw.py \
            --input-dir artifacts/excalidraw \
            --output artifacts/excalidraw_categories \
            --group-by category \
            --columns 8 \
            --cell-width 220 \
            --cell-height 240 \
            --padding 24 \
            --label-gap 12 \
            --exclude-regular

      - name: Build full icon library bundle
        run: |
          python scripts/combine_excalidraw.py \
            --input-dir artifacts/excalidraw \
            --output artifacts/excalidraw_library/icons.excalidrawlib \
            --library \
            --exclude-regular

      - name: Build category libraries
        run: |
          python scripts/combine_excalidraw.py \
            --input-dir artifacts/excalidraw \
            --output artifacts/excalidraw_library_categories \
            --group-by category \
            --library \
            --exclude-regular

      - name: Combine all emojis into a single board
        run: |
          python scripts/combine_excalidraw.py \
            --input-dir artifacts/excalidraw_emojis \
            --output artifacts/emoji_library.excalidraw \
            --group-by none \
            --columns 6 \
            --cell-width 180 \
            --cell-height 160 \
            --padding 30 \
            --label-gap 25

      - name: Group emojis into categories
        run: |
          python scripts/combine_excalidraw.py \
            --input-dir artifacts/excalidraw_emojis \
            --output artifacts/excalidraw_emoji_categories \
            --group-by category \
            --columns 5 \
            --cell-width 200 \
            --cell-height 180 \
            --padding 35 \
            --label-gap 25

      - name: Build emoji library bundle
        run: |
          python scripts/combine_excalidraw.py \
            --input-dir artifacts/excalidraw_emojis \
            --output artifacts/excalidraw_emoji_library/emojis.excalidrawlib \
            --library \
            --columns 6 \
            --cell-width 180 \
            --cell-height 160 \
            --padding 30 \
            --label-gap 25

      - name: Build emoji category libraries
        run: |
          python scripts/combine_excalidraw.py \
            --input-dir artifacts/excalidraw_emojis \
            --output artifacts/excalidraw_emoji_library_categories \
            --group-by category \
            --library \
            --columns 5 \
            --cell-width 200 \
            --cell-height 180 \
            --padding 35 \
            --label-gap 25

      - name: Package release assets
        run: |
          mkdir -p dist
          # Icon packages
          zip -r dist/excalidraw-scenes.zip artifacts/excalidraw
          zip -r dist/excalidraw-groups-categories.zip artifacts/excalidraw_categories
          zip -r dist/excalidraw-library.zip artifacts/excalidraw_library
          zip -r dist/excalidraw-library-categories.zip artifacts/excalidraw_library_categories
          cp artifacts/all_icons.excalidraw dist/all_icons.excalidraw
          cp artifacts/excalidraw_library/icons.excalidrawlib dist/icons-library.excalidrawlib
          cp metadata/icons.json dist/icons-metadata.json
          # Emoji packages
          zip -r dist/excalidraw-emoji-scenes.zip artifacts/excalidraw_emojis
          zip -r dist/excalidraw-emoji-categories.zip artifacts/excalidraw_emoji_categories
          zip -r dist/excalidraw-emoji-library.zip artifacts/excalidraw_emoji_library
          zip -r dist/excalidraw-emoji-library-categories.zip artifacts/excalidraw_emoji_library_categories
          cp artifacts/emoji_library.excalidraw dist/emoji_library.excalidraw
          cp artifacts/excalidraw_emoji_library/emojis.excalidrawlib dist/emojis-library.excalidrawlib
          cp metadata/emojis.json dist/emojis-metadata.json

      - name: Upload workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: excalidraw-release-assets
          path: dist

      - name: Determine release tag
        id: release_meta
        run: |
          VERSION="excalidraw-$(date -u +'%Y%m%d-%H%M%SZ')"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_meta.outputs.version }}
          release_name: Fluent UI Icons & Emojis for Excalidraw ${{ steps.release_meta.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload scenes archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/excalidraw-scenes.zip
          asset_name: excalidraw-scenes-${{ steps.release_meta.outputs.version }}.zip
          asset_content_type: application/zip

      - name: Upload grouped boards archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/excalidraw-groups-categories.zip
          asset_name: excalidraw-groups-categories-${{ steps.release_meta.outputs.version }}.zip
          asset_content_type: application/zip

      - name: Upload library archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/excalidraw-library.zip
          asset_name: excalidraw-library-${{ steps.release_meta.outputs.version }}.zip
          asset_content_type: application/zip

      - name: Upload category library archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/excalidraw-library-categories.zip
          asset_name: excalidraw-library-categories-${{ steps.release_meta.outputs.version }}.zip
          asset_content_type: application/zip

      - name: Upload combined board
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/all_icons.excalidraw
          asset_name: all-icons-${{ steps.release_meta.outputs.version }}.excalidraw
          asset_content_type: application/json

      - name: Upload icon library
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/icons-library.excalidrawlib
          asset_name: icons-library-${{ steps.release_meta.outputs.version }}.excalidrawlib
          asset_content_type: application/json

      - name: Upload icon metadata
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/icons-metadata.json
          asset_name: icons-metadata-${{ steps.release_meta.outputs.version }}.json
          asset_content_type: application/json

      - name: Upload emoji scenes archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/excalidraw-emoji-scenes.zip
          asset_name: excalidraw-emoji-scenes-${{ steps.release_meta.outputs.version }}.zip
          asset_content_type: application/zip

      - name: Upload emoji category boards archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/excalidraw-emoji-categories.zip
          asset_name: excalidraw-emoji-categories-${{ steps.release_meta.outputs.version }}.zip
          asset_content_type: application/zip

      - name: Upload emoji library archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/excalidraw-emoji-library.zip
          asset_name: excalidraw-emoji-library-${{ steps.release_meta.outputs.version }}.zip
          asset_content_type: application/zip

      - name: Upload emoji category library archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/excalidraw-emoji-library-categories.zip
          asset_name: excalidraw-emoji-library-categories-${{ steps.release_meta.outputs.version }}.zip
          asset_content_type: application/zip

      - name: Upload combined emoji board
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/emoji_library.excalidraw
          asset_name: emoji-library-${{ steps.release_meta.outputs.version }}.excalidraw
          asset_content_type: application/json

      - name: Upload emoji library
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/emojis-library.excalidrawlib
          asset_name: emojis-library-${{ steps.release_meta.outputs.version }}.excalidrawlib
          asset_content_type: application/json

      - name: Upload emoji metadata
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/emojis-metadata.json
          asset_name: emojis-metadata-${{ steps.release_meta.outputs.version }}.json
          asset_content_type: application/json
